services:
  api:
    image: vyctor88/api-livros:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0.41
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: biblioteca

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
volumes:
  dbbase: