spring:
  application:
    name: Api de livros
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca
    username: root
    password: Vk 07081415
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true